### ISSUE TITLE
Max Processors

### ISSUE THREAD

**Issue by boldtrn** [MorbZ/OsmPoisPbf#15]
Nice progress lately.

In the README you specify: 

> Number of CPU cores (max. 4)

But in the Benchmark you show up to 8 CPUs, this is a bit weird.

**Comment by MorbZ** [comment]
`Number of CPU cores (max. 4)` is the default value for processors. You can however set a higher number manually.

**Comment by boldtrn** [comment]
Ah ok, max. 4 sounds like an absolute maximum, as if you can only set 1-4.
