### ISSUE TITLE
Readme formatting is broken

### ISSUE THREAD

**Issue by boldtrn** [MorbZ/OsmPoisPbf#17]
The table of the Parameters in the Readme is somehow broken.

**Comment by pintergreg** [comment]
GitHub formalized the GitHub Flavored Markdown and the specs changed a little bit. I [sent a pull request](https://github.com/MorbZ/OsmPoisPbf/pull/18) correcting the table.

**Comment by MorbZ** [comment]
@pintergreg Thanks!
