### ISSUE TITLE
Extract from specific language

### ISSUE THREAD

**Issue by ctepeo** [MorbZ/OsmPoisPbf#4]
Could You add a language parameter to command? Some POI Names has been translated to specific language and it'll be good to get it in csv from Your application.

For example Louvre (https://www.openstreetmap.org/relation/4740895)
```name	Musée du Louvre,
name:de	Museum des Louvre,
name:en	Louvre Museum,
name:es	Museo del Louvre,
name:ja	ルーブル美術館,
name:pt	Museu do Louvre,
name:ru	Лувр,
name:zh	卢浮宫博物馆```

It'll be cool to add parameter such as ```--language=ru``` and receive one more column at csv

`POI_TYPE | OSM_ID | LAT | LON | NAME_DEFAULT | _NAME_RU_`

If there's no "name:ru" tag it can be simply empty.

**Comment by MorbZ** [comment]
Additional output tags can be defined via the `--outputTags ` parameter.
