### ISSUE TITLE
Extract of poi without name ?

### ISSUE THREAD

**Issue by sebheitzmann** [MorbZ/OsmPoisPbf#7]
I think that the tool don't extract poi that does not have name. 

Is that exact ?

**Comment by MorbZ** [comment]
By default the `--requiredTags` parameter is set to `name`, so that only POIs with a name tag will be extracted. You can however provide the `--requiredTags` parameter without a following value to extract all POIs.

**Comment by sebheitzmann** [comment]
Ok with that params but when I use --requiredTags= I got no Poi at all.

**Comment by sebheitzmann** [comment]
java -Xmx9g -jar osmpois.jar -rt "" -r --filterFile=filters.txt --outputFile=poi.csv mulhouse.osm.pbf


Give me this

OsmPoisPbf v1.1 started
OSMonaut started
Scanning relations...
Scanning ways...
Final scan...
0 POIs found
Elapsed time in milliseconds: 5829

**Comment by MorbZ** [comment]
Use `--requiredTags` without the equals sign.
