### ISSUE TITLE
Longitude incorrect in output file

### ISSUE THREAD

**Issue by dagobah19** [MorbZ/OsmPoisPbf#9]
I am using osmpoispbf to extract pois from geofrabik pbf extracts. All appears okay when I first open the resulting csv file. About 3/4 of the way through the CSV, the longitude suddenly changes to a strange value that isn't close to the correct value. For example, running the pois against florida around line 60355:

![image](https://cloud.githubusercontent.com/assets/19868110/15983136/cdc441b8-2f6b-11e6-98dc-05f459d789ce.png)

Note the dramatic shift from the correct long to a number that is far off. The rest of the file has this problem. This has happened with multiple states. Here is the command I am using to generate the file:

java -Xmx1300m -jar osmpois.jar -ot name,amenity,building,historic,leisure,office,shop,tourism,waterway,addr:housenumber,addr:street,addr:city,addr:postcode,addr:province,addr:state,addr:country florida-latest.osm.pbf

File downloaded from http://download.geofabrik.de/north-america.html

I did try to create my own file using the export from openstreetmap org, then converting it to a pbf and running the pois against it, but I still get the same behavior about 1/2 way through. Attached is the result of a pbf converted and imported from openstreetmap for the buffalo, ny region. Line 386 is where it suddenly changes.

![image](https://cloud.githubusercontent.com/assets/19868110/15983227/94917c0a-2f6e-11e6-8fb8-36802c738972.png)

[map.pdf](https://github.com/MorbZ/OsmPoisPbf/files/310096/map.pdf)
(Sorry, it won't accept csv so I had to pdf the file)

**Comment by MorbZ** [comment]
That might have been caused by a bug in Osmonaut that [has been fixed](https://github.com/MorbZ/OSMonaut/commit/592c697d0435d992c2472a159e3fc95029ae5db3) but the fix isn't used in Osmpoispbf already. The shift seems to appear when the processing is transitioning from nodes (N...) to ways (W...). I'll have a look into it.
